#.travis.yml
dist: bionic

script:
  - hostname

after_success:
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 _utils/merge.py

notifications:
  slack:
    secure: "jMl3QRRfBTRglD6lVeYQSM+ljUsVp37UUuZixVDAaMvLF9m64GvyCbbc8n8AbojZxn7DpMR1mRvCUc3EmVG4z+wFjpvrfbWNFU/rjvRmoxkSLdbEYtI+4Nk+eZPYe4HjDXNL1M6KLCNBPVGgpaiogYwKCQviaLKUxeo40uW76ceKas1SnzQI6OFU8n25ixj9CNM+4/y4TCHpLvW4DJr7Ud4UaYJRCJPwCQIi0e1s/PRMeGmVixvIne1KmrWV/iQwcmBcPfitluRkDHXV4zyB5KnL9W50hzfksR1ttUYOZniW0lemxrLeEQ/wBkt4OuXxtYwWn5G2kL71PqRM2L+RVGk5Q0o9AJiuUhoifgVzO8kgDK00hjGjpiFdMGj4BgNyYaX6Dv/dy7I7XAOqIOqzTn82PvKm55/NVudYkt6Iu5GU5uOFxCHF+IsBMCMOBl942s0Dp2rEa1bwcUa4twrmqRLRvv2eKeTJSBZWYQ5tHTC6JF8OgoM5SIldqbzqPsueiTPcWj72RnTyGd/l9lV0B3umHwa9KqCRTbF2CGRYog0D131+wy6fRnyKGEPLWsmOI5eA6YQQBo/7kiKvcoVn9u9VWKXzz1+ctTq1i/d2WGA4nZ9uoyU4/9Zj8ZnUgtvVsOsMeao27UaP9Nflg4D2deR51IE0lJTzgNFoc0r30s0="
