
git config -f .gitmodules submodule.96boards/documentation.shallow true
git config -f .gitmodules submodule.adafruit/4-Channel-Level-Shifter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_1.8_Inch_TFT_Breakout_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_2.8_Inch_TFT_Shield_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_ADXL343_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_ADXL345_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_Atmega32u4_Breakout_Board.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_Breadboard_NeoPixel_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_CC3000_Shield_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_FTDI-Friend-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_MCP73833_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_MintyBoost_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit_USB_Boarduino_PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-0.96-160x80-TFT-Display-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.14-inch-240x135-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.27inch-Color-OLED-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.3-inch-240x240-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.3inch-128x64-Mono-OLED-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.44-TFT-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.54-inch-240x240-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.5inch-Color-OLED-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-1.8-TFT-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-128x32-I2C-OLED-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-128x32-SPI-OLED-breakout-board-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-128x64-Monochrome-OLED-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-128x64-OLED-Bonnet-for-Raspberry-Pi-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-16-Channel-PWM-Servo-Driver-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-2.0-inch-240x320-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-2.4-TFT-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-2.4-TFT-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-2.8-TFT-Shield-v2-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-2.8-TFT-with-Capacitive-Touch-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-3.5in-TFT-Featherwing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-5-HDMI-Backpack-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-50pin-to-40pin-TFT-with-AR1100-Adapter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-7-HDMI-Backpack-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-9-DOF-and-10-DOF-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-96x64-RGB-OLED-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AD8495-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Adalogger-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ADT7410-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ADXL343-ADT7410-Featherwing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Airlift-Bitsy-Add-On-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AirLift-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AirLift-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Airlift-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ALS-PT19-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AMG8833-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Analog-Accelerometers-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Animated-Eyes-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-APDS9960-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AR1100-Resistive-Touch-Controller-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Arcade-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-AS7262-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ATECC608-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ATWINC1500-WiFi-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Audio-FX-Sound-Board-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BeagleBone-ProtoBoard-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-Classic-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-EZ-Key-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-EZ-Link-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-Micro-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-nRF8001-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-SPI-Friend-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-UART-Friend-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Bluefruit-LE-USB-Friend-and-Sniffer-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BME280-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BME680-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BMP085-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BMP180-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BMP183-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BMP280-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BMP388-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-BNO055-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-CAP1188-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Capacitive-Touch-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-CC3000-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-CCS811-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-CharliePlex-Bonnet-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Circuit-Playground-Bluefruit-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Circuit-Playground-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Circuit-Playground-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Circuit-Playground-Tri-Color-E-Ink-Gizmo-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-CP2104-Friend-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Cupcade-Adapter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DC-Stepper-Motor-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DC-Stepper-Motor-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DotStar-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DPI-Kippah-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DragonTail-for-micro-bit-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DRV2605-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DRV8833-Motor-Driver-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DRV8871-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DS2413-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DS3231-Precision-RTC-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DS3231-Precision-RTC-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-DS3502-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-E-Paper-Display-Breakout-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ESP32-HUZZAH-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Ethernet-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-328P-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-32u4-Adalogger-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-32u4-Basic-Proto-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-32u4-Bluefruit-LE-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-32u4-FONA-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-32u4-RFM-LoRa-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-ESP8266-HUZZAH-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-Adalogger-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-Basic-Proto-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-Bluefruit-LE-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-RFM-LoRa-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M0-WiFi-WINC1500-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Feather-M4-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-Bluefruit-LE-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-LSM303-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-LSM9DS0-9DOF-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-Sewable-3-Pin-JST-Wiring-Adapter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-Si1145-Light-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-TCS34725-Color-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Flora-TSL2561-Lux-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FONA-800-GSM-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FONA-800-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FONA-808-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FONA-SIMCOM-3G-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FONA808-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FPC-SMT-Adapter-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FRAM-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FT232H-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-FXOS8700-FXAS21002-9-DoF-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-GA1A1S202WP-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Gemma-M0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Gemma-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-GPIO-Expander-Bonnet-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-GPS-Logger-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Grand-Central-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-GUVA-Analog-UV-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Hallowing-M0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Hallowing-M4-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-HDC1008-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-HMC5883-Mag-Compass-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-HTU21D-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Huzzah-ESP8266-Basic-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-HUZZAH32-ESP32-Feather-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-I2C-SPI-LCD-Backpack-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-I2S-Audio-Bonnet-for-Raspberry-Pi-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-I2S-Microphone-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-INA169-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-INA219-Current-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-INA260-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-IS31FL3731-CharliePlex-LED-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ISP-SWD-and-JTAG-Breakout-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ItsyBitsy-32u4-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ItsyBitsy-M0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-ItsyBitsy-M4-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Joy-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Joy-Featherwing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-L3GD20-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LED-Backpack-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LED-Sequin-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LIS3DH-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LM3671-Buck-Converter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LM4040-Voltage-Reference-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Low-profile-microSD-to-SD-Adapter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LPS3X-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LSM303-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LSM303AGR-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LSM6DSOX-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LSM9DS0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-LSM9DS1-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX31850-thermocouple-breakout-board.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX31855-breakout-board.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX31856-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX31865-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX4466-Electret-Mic-Amplifier-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX6675-Breakout-Board-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX9744-Amplifier-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX9814-AGC-Microphone-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX98306-Class-D-Amp-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MAX98357-I2S-Amp-Breakout.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MCP4725-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MCP9600-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MCP9808-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Menta-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-METRO-328-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Metro-M0-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Metro-M4-Express-AirLift-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Metro-M4-Express-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MicroLipo-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MiCS-5524-Gas-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Mini-Analog-Thumbstick-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Mini-PiTFT-240x135-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Mini-TFT-with-Joystick-Featherwing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MLX90393-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MMA8451-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MONSTER-M4SK-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Motor-Shield-V2-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPL115A2-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPL3115A2-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPR121-Capacitive-Touch-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPR121-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPRLS-Pressure-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MPU6050-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-MSA301-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Music-Maker-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Music-Maker-MP3-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-NeoPixel-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-NeoPixel-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-NeoPXL8-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-NeoTrellis-4x4-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-NeoTrellis-M4-PCB-and-Enclosure.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-nRF52-Bluefruit-Feather-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-OLED-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PA1010D-Mini-GPS-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PAM8302-Mono-Amplifier-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Particle-Spark-Neopixel-Ring-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PCB-Ruler.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PCF8523-RTC-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Perma-Proto-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Perma-Proto-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Perma-Proto-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Perma-Proto-Pi-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Pi-Cobber-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiGRRL-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiOLED-128x32-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-pIRKey-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiRTC-RTC-for-Raspberry-Pi-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-2.2-Inch-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-2.4-Inch-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-2.8-inch-Display-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-3.5-Plus-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-Plus-2.8-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiTFT-Plus-3.2-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PiUART-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PN532-RFID-NFC-Breakout.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Power-Relay-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PowerBoost-1000-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PowerBoost-500-Basic-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PowerBoost-500-Charger-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PowerBoost-500-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Pro-Trinket-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Prop-Maker-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Proto-Plate-for-Beagle-Bone-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Proto-Screwshield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Proto-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Prototyping-Pi-Plate-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Push-Button-Power-Switch-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PWM-Servo-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PyBadge-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PyGamer-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PyPortal-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-PyRuler-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Qualia-Driver-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RA8875-Breakout-Board-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Radio-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Radio-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Relay-FeatherWing-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RFM-LoRa-Radio-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RGB-LCD-shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RGB-Matrix-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RGB-Matrix-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RGB-Matrix-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-RGB-Matrix-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-SAMD09-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Servo-HAT-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-SHT31-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Si1145-Light-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Si4713-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Si5351A-Clock-Generator-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Si7021-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-SMT-Breakout-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-SPW2430-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Standalone-Capacitive-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-STEMMA-Non-Latching-Mini-Relay-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-STEMMA-Soil-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-STEMMA-Speaker-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Stereo-Speaker-Bonnet-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-STMPE610-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TB6612-Motor-Driver-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TCA9548A-I2C-Multiplexer-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TCS34725-Color-Sensor-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Teensy-3.x-Feather-Adapter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Terminal-Block-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TFP401-HDMI-To-40Pin-TFT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TFT-Gizmo-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TLC5947-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TLC59711-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TLV493D-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TMP006-and-TMP007-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TPA2012-or-TS2012-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TPA2016-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TPL5110-Power-Timer-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TPL5111-Reset-Enable-Timer-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Trinket-M0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Trinket-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TSL2591-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TXB0104-Level-Shifter-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-TXB0108-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-UDA1334A-I2S-Stereo-DAC-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Ultimate-GPS-FeatherWing-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Ultimate-GPS-HAT-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-USB-C-Downstream-Breakout.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-USB-Isolator-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-USB-LiIon-LiPoly-Charger-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-USB-Power-Gauge-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-USB-Serial-RGB-Character-Backpack-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VCNL4040-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VCNL40X0-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VEML6070-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VEML6075-UV-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VEML7700-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-Verter-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VL53L0X-ToF-Distance-Sensor-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-VS1053-Breakout-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-WICED-WiFi-Feather-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Adafruit-WINC1500-Shield-PCB.shallow true
git config -f .gitmodules submodule.adafruit/ADS1X15-Breakout-Board-PCBs.shallow true
git config -f .gitmodules submodule.adafruit/cookiecutter-adafruit-pcb.shallow true
git config -f .gitmodules submodule.adafruit/DotStar-2020-8x8-Matrix-PCB.shallow true
git config -f .gitmodules submodule.adafruit/DS1307-breakout-board.shallow true
git config -f .gitmodules submodule.adafruit/Feather-ICE40-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Feather-RISC-V-PCB.shallow true
git config -f .gitmodules submodule.adafruit/Pixie-3W-Smart-LED-PCB.shallow true
git config -f .gitmodules submodule.adafruit/TSL2561-breakout-board-PCB.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-MINI-UPS-V2.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-Relay-V1.2.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-SKR-mini-E3.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-SKR-MINI-V1.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-SKR-PRO-V1.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-SKR-V1.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-ST820-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TFT24-V1.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TFT35-V3.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2130-V1.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2130-V2.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2130-V3.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2208-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2208-V2.1.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2208-V3.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2209-V1.2.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC2225-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC5160-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIGTREETECH-TMC5161-V1.0.shallow true
git config -f .gitmodules submodule.bigtreetech/BIQU-Thunder.shallow true
git config -f .gitmodules submodule.bigtreetech/ramps-1.6.shallow true
git config -f .gitmodules submodule.bigtreetech/Tango-3D-Printer-Motherboard.shallow true
git config -f .gitmodules submodule.bigtreetech/TMC2209-V1.1.shallow true
git config -f .gitmodules submodule.BPI-SINOVOIP/BPI-Schematics.shallow true
git config -f .gitmodules submodule.dtnking/Micro-USB-Connector.shallow true
git config -f .gitmodules submodule.dtnking/PCB-RJ12.shallow true
git config -f .gitmodules submodule.dtnking/PCB-STM32F401CCT6_Development_Board.shallow true
git config -f .gitmodules submodule.dtnking/Reflow-Oven.shallow true
git config -f .gitmodules submodule.dtnking/STLINK_V2-1.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-enclosures.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-kit-10.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-kit-20.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-kit-21.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-kit-gases-pro-board.shallow true
git config -f .gitmodules submodule.fablabcn/smartcitizen-kit-pm-board.shallow true
git config -f .gitmodules submodule.freetronics/RELAY16MEGA.shallow true
git config -f .gitmodules submodule.freetronics/RELAYSHIELD16.shallow true
git config -f .gitmodules submodule.freetronics/USBSerial.shallow true
git config -f .gitmodules submodule.hallard/LoRasPI.shallow true
git config -f .gitmodules submodule.hallard/NodeMCU-Gateway.shallow true
git config -f .gitmodules submodule.hallard/Particle-Gateway.shallow true
git config -f .gitmodules submodule.hallard/RM1xx-Breakout.shallow true
git config -f .gitmodules submodule.hallard/WeMos-Lora.shallow true
git config -f .gitmodules submodule.hallard/WeMos-Matrix-Shield.shallow true
git config -f .gitmodules submodule.hallard/WeMos-RN2483.shallow true
git config -f .gitmodules submodule.hallard/WeMos-shield.shallow true
git config -f .gitmodules submodule.IdleHandsProject/CC110L-Breakout.shallow true
git config -f .gitmodules submodule.IdleHandsProject/espeverywhere.shallow true
git config -f .gitmodules submodule.IdleHandsProject/makennbot.shallow true
git config -f .gitmodules submodule.IdleHandsProject/PiZeroHub.shallow true
git config -f .gitmodules submodule.IdleHandsProject/samd_hcc_mod.shallow true
git config -f .gitmodules submodule.IdleHandsProject/thePIDDYBOT.shallow true
git config -f .gitmodules submodule.IdleHandsProject/wind_breakout.shallow true
git config -f .gitmodules submodule.im-tomu/tomu-hardware.shallow true
git config -f .gitmodules submodule.iotmakervn/esp32-cellular-shield.shallow true
git config -f .gitmodules submodule.iotmakervn/esp32-connectivity-shield.shallow true
git config -f .gitmodules submodule.iotmakervn/gsm-iot-core-hw.shallow true
git config -f .gitmodules submodule.iotmakervn/iot-gprs-wifi-uno-hw.shallow true
git config -f .gitmodules submodule.iotmakervn/iot-wifi-uno-hw.shallow true
git config -f .gitmodules submodule.iotmakervn/iotmaker-unox.shallow true
git config -f .gitmodules submodule.iotmakervn/VM-sensor-PT1000.shallow true
git config -f .gitmodules submodule.m5stack/M5-3D_and_PCB.shallow true
git config -f .gitmodules submodule.m5stack/M5-Schematic.shallow true
git config -f .gitmodules submodule.m5stack/M5Stack_TFT_ILI9341.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-Robin-lite3.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-Robin-mini.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-Robin-Nano.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-Robin-Pro.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-SERVO42A.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-SERVO42B.shallow true
git config -f .gitmodules submodule.makerbase-mks/MKS-SERVO57A.shallow true
git config -f .gitmodules submodule.mattdibi/yampad.shallow true
git config -f .gitmodules submodule.mysensors/SensebenderMicro.shallow true
git config -f .gitmodules submodule.najnesnaj/stm8-kicad-design-se8R01-pcb.shallow true
git config -f .gitmodules submodule.OLIMEX/NB-IoT.shallow true
git config -f .gitmodules submodule.OLIMEX/OLIMEXINO-2560.shallow true
git config -f .gitmodules submodule.prusa3d/CW-01-LED-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/CW-CONTROLLER-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/IR-MH-sensor-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/MKxS-IR-sensor.shallow true
git config -f .gitmodules submodule.prusa3d/MM-control-2.0.shallow true
git config -f .gitmodules submodule.prusa3d/SL-CONTROLLER-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/SL-LED-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/SL-PS-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/SL-USB-PCB.shallow true
git config -f .gitmodules submodule.prusa3d/SL-UVcoin-sensor-PCB.shallow true
git config -f .gitmodules submodule.raphaelchang/dragonquad-hardware.shallow true
git config -f .gitmodules submodule.sparkfun/32U4_Breakout_Board.shallow true
git config -f .gitmodules submodule.sparkfun/BMP085_Breakout.shallow true
git config -f .gitmodules submodule.sparkfun/CP2102_Breakout.shallow true
git config -f .gitmodules submodule.sparkfun/ESP32_LoRa_1Ch_Gateway.shallow true
git config -f .gitmodules submodule.sparkfun/ESP32_Power_Control_Shield.shallow true
git config -f .gitmodules submodule.sparkfun/ESP8266_Thing_Dev.shallow true
git config -f .gitmodules submodule.sparkfun/ESP8266_Thing.shallow true
git config -f .gitmodules submodule.sparkfun/GPS_Breakout.shallow true
git config -f .gitmodules submodule.sparkfun/LCD_TFT_Breakout_1in8_128x160.shallow true
git config -f .gitmodules submodule.sparkfun/SD-MMC_Breakout.shallow true
git config -f .gitmodules submodule.svcguy/LoRaWAN-Feather-Hardware.shallow true
git config -f .gitmodules submodule.Tinkerforge/ac-current-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/accelerometer-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/accelerometer-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/adapter-xmc-flash.shallow true
git config -f .gitmodules submodule.Tinkerforge/air-quality-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ambient-light-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ambient-light-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ambient-light-v3-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-in-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-in-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-in-v3-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-out-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-out-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/analog-out-v3-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/barometer-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/barometer-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/battery-holder.shallow true
git config -f .gitmodules submodule.Tinkerforge/blinkenlights.shallow true
git config -f .gitmodules submodule.Tinkerforge/bootstrapper_xmc.shallow true
git config -f .gitmodules submodule.Tinkerforge/breakout_xmc1300.shallow true
git config -f .gitmodules submodule.Tinkerforge/breakout-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/breakout-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/breakout-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/brick-mqtt-proxy.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickboot.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickd.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickletboot_samd.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickletboot_xmc.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickletlib.shallow true
git config -f .gitmodules submodule.Tinkerforge/bricklib.shallow true
git config -f .gitmodules submodule.Tinkerforge/bricklib2.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickv.com.shallow true
git config -f .gitmodules submodule.Tinkerforge/brickv.shallow true
git config -f .gitmodules submodule.Tinkerforge/camera-slider.shallow true
git config -f .gitmodules submodule.Tinkerforge/can-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/can-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/cases.shallow true
git config -f .gitmodules submodule.Tinkerforge/chibi-extension.shallow true
git config -f .gitmodules submodule.Tinkerforge/co2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/co2-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/color-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/color-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/compass-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/current12-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/current25-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/daemonlib.shallow true
git config -f .gitmodules submodule.Tinkerforge/dc-adapter.shallow true
git config -f .gitmodules submodule.Tinkerforge/dc-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/dc-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/debug-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/distance-ir-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/distance-ir-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/distance-us-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/distance-us-v2-bricklet-techniker.shallow true
git config -f .gitmodules submodule.Tinkerforge/distance-us-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/dmx-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/dual-button-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/dual-button-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/dual-relay-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/dust-detector-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/e-paper-296x128-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/energy-monitor-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ethernet-extension.shallow true
git config -f .gitmodules submodule.Tinkerforge/fingerprint-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/gas-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/gas-detector-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/gps-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/gps-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/hall-effect-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/hall-effect-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/humidity-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/humidity-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-analog-out-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-analog-out-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-counter-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-digital-in-4-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-digital-in-4-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-digital-out-4-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-digital-out-4-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-digital-out-hs-4-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-dual-0-20ma-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-dual-0-20ma-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-dual-analog-in-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-dual-analog-in-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-dual-relay-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-encoder-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-push-pull-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-quad-relay-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/industrial-quad-relay-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/internet-of-things.shallow true
git config -f .gitmodules submodule.Tinkerforge/joystick-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/joystick-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/laser-range-finder-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/laser-range-finder-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/lcd-128x64-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/lcd-16x2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/lcd-20x4-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/led-strip-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/led-strip-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/line-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/linear-poti-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/linear-poti-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/load-cell-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/load-cell-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/master-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/midi-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/moisture-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/moisture-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/motion-detector-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/motion-detector-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/motorized-linear-poti-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/multi-touch-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/multi-touch-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/nfc-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/nfc-rfid-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/o3-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/oled-128x64-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/oled-128x64-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/oled-64x48-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/one-wire-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/outdoor-weather-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ozone-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/particulate-matter-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/piezo-buzzer-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/piezo-speaker-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/piezo-speaker-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/power-supply-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/pressure-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ptc-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/ptc-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/real-time-clock-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/real-time-clock-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/red-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/remote-switch-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rgb-led-matrix-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rgb-led-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rotary-encoder-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rotary-encoder-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rotary-poti-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rotary-poti-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rs232-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rs232-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/rs485-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/servo-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/servo-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/silent-stepper-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/silent-stepper-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/solid-state-relay-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/solid-state-relay-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/sound-intensity-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/sound-pressure-level-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/step-down-powersupply.shallow true
git config -f .gitmodules submodule.Tinkerforge/stepper-brick.shallow true
git config -f .gitmodules submodule.Tinkerforge/temperature-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/temperature-ir-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/temperature-ir-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/temperature-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/thermocouple-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/uv-light-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/uv-light-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/voltage-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/voltage-current-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/voltage-current-v2-bricklet.shallow true
git config -f .gitmodules submodule.Tinkerforge/weather-station.shallow true
git config -f .gitmodules submodule.Tinkerforge/wifi-v2-extension.shallow true
git config -f .gitmodules submodule.Tinkerforge/xmc1400-breakout-bricklet.shallow true
